apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-b
  namespace: project-b
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-b
  template:
    metadata:
      labels:
        app: web-b
    spec:
      containers:
      - name: web
        image: public.ecr.aws/d0z6a9w2/project-b:latest
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: ecr-secret
